name: pretty_diff_text
description: PrettyDiffText is wrapper of RichText which shows differences between two texts visually. It uses Google's diff-match-patch library.
version: 2.0.0
homepage: https://github.com/zmeid/pretty-diff-text

environment:
  sdk: ">=3.2.0-0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  diff_match_patch: ^0.4.1